package com.example.domain.service

import com.example.domain.model.AiModelConfig
import com.example.domain.model.AiStreamChunk
import com.example.domain.model.ChatMessage
import kotlinx.coroutines.flow.Flow

/**
 * Clean architectural abstraction for AI model execution.
 * Allows effortless swapping or hybrid combining of cloud AI APIs (e.g. Gemini, Anthropic, OpenAI),
 * local on-device models, or mock implementations without modifying ViewModel or UI layers.
 */
interface AiService {
    /**
     * Executes a one-shot completion for the given conversation and prompt.
     */
    suspend fun generateResponse(
        conversationId: String,
        prompt: String,
        history: List<ChatMessage>,
        config: AiModelConfig
    ): Result<String>

    /**
     * Streams tokens as they are generated by the underlying model.
     */
    fun generateStream(
        conversationId: String,
        prompt: String,
        history: List<ChatMessage>,
        config: AiModelConfig
    ): Flow<AiStreamChunk>

    /**
     * Checks if the AI service provider is configured and available.
     */
    suspend fun isAvailable(): Boolean
}
