package com.example.domain.service

import com.example.domain.model.AiModelConfig
import com.example.domain.model.AiStreamChunk
import com.example.domain.model.Attachment
import com.example.domain.model.ChatMessage
import kotlinx.coroutines.flow.Flow

/**
 * Clean architectural abstraction for AI model execution.
 * Supports text, multimodal images, PDFs, document files, and Google Search grounding.
 */
interface AiService {
    /**
     * Executes a one-shot completion for the given conversation, prompt, optional attachments,
     * and search grounding preference.
     */
    suspend fun generateResponse(
        conversationId: String,
        prompt: String,
        history: List<ChatMessage>,
        config: AiModelConfig,
        attachments: List<Attachment> = emptyList(),
        enableSearch: Boolean = false
    ): Result<String>

    /**
     * Streams tokens and grounding citations as they are generated by the underlying model.
     */
    fun generateStream(
        conversationId: String,
        prompt: String,
        history: List<ChatMessage>,
        config: AiModelConfig,
        attachments: List<Attachment> = emptyList(),
        enableSearch: Boolean = false
    ): Flow<AiStreamChunk>

    /**
     * Checks if the AI service provider is configured and available.
     */
    suspend fun isAvailable(): Boolean
}
